In [1]:
import numpy as np

In [3]:
X = np.array([10,20,30,40,50])
print(X[2], X[1:3], sep="\n\n")

30

[20 30]


In [4]:
X[1:3]=99
X

array([10, 99, 99, 40, 50])

In [5]:
subarray = X[1:3]
subarray

array([99, 99])

In [6]:
subarray[0]=199
X

array([ 10, 199,  99,  40,  50])

In [7]:
X = np.array([[10,20,30,40],[50,60,70,80]])
X

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
print(X[0], X[1], sep="\n\n")

[10 20 30 40]

[50 60 70 80]


In [9]:
print(X[:,2], X[:,3], sep="\n\n")

[30 70]

[40 80]


In [11]:
X[:,1:3]

array([[20, 30],
       [60, 70]])

In [12]:
X[0,1:3]

array([20, 30])

In [6]:
X = np.array([[[10,20,30,40],[50,60,70,80]],[[100,200,300,400],[500,600,700,800]]])
X

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80]],

       [[100, 200, 300, 400],
        [500, 600, 700, 800]]])

In [7]:
print(X[0], X[1], sep="\n\n")

[[10 20 30 40]
 [50 60 70 80]]

[[100 200 300 400]
 [500 600 700 800]]


In [8]:
print(X[0,1], X[1,0], sep="\n\n")

[50 60 70 80]

[100 200 300 400]


In [10]:
print(X[0,:,3], X[1,:,2], sep="\n\n")

[40 80]

[300 700]


In [11]:
X[1,0,2]

300

In [17]:
X=np.random.rand(4,3)
Yrow=np.array([True, False, True, False])
Ycol=np.array([True, False, True])
print(X, X[Yrow==True], X[:, Ycol==True], sep="\n\n")

[[0.30236822 0.1637452  0.78361766]
 [0.71098286 0.53290113 0.64216861]
 [0.2920466  0.00695872 0.37830307]
 [0.66352843 0.76664034 0.01142493]]

[[0.30236822 0.1637452  0.78361766]
 [0.2920466  0.00695872 0.37830307]]

[[0.30236822 0.78361766]
 [0.71098286 0.64216861]
 [0.2920466  0.37830307]
 [0.66352843 0.01142493]]


In [19]:
X=np.random.rand(4,3)
X

array([[0.98836029, 0.85297278, 0.42589043],
       [0.49405286, 0.65802824, 0.9655651 ],
       [0.83053895, 0.9848238 , 0.31258058],
       [0.89935767, 0.79199459, 0.79057659]])

In [29]:
X[X<0.4]

array([0.31258058])

In [37]:
X[X<0.4] = 99

In [38]:
X

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]])

In [40]:
X = np.random.rand(8,4)
X

array([[0.24860556, 0.70247267, 0.8665756 , 0.92908556],
       [0.73844554, 0.52662312, 0.84963643, 0.73430832],
       [0.10072856, 0.83434816, 0.43581984, 0.25082671],
       [0.69320226, 0.41226041, 0.55082993, 0.45958315],
       [0.8428631 , 0.35177266, 0.86294005, 0.25229424],
       [0.12224095, 0.27252694, 0.79530919, 0.47453337],
       [0.36628278, 0.87805397, 0.00792831, 0.01589717],
       [0.37507002, 0.16354021, 0.72375131, 0.27031079]])

In [42]:
X[[0,1], [0,1]]

array([0.24860556, 0.52662312])

In [43]:
X[[2, 4, 5]]

array([[0.10072856, 0.83434816, 0.43581984, 0.25082671],
       [0.8428631 , 0.35177266, 0.86294005, 0.25229424],
       [0.12224095, 0.27252694, 0.79530919, 0.47453337]])

In [44]:
X[[2, 4, 5]][:,[1,2]]

array([[0.83434816, 0.43581984],
       [0.35177266, 0.86294005],
       [0.27252694, 0.79530919]])

In [45]:
X[[2, 4, 5]][:,[1,2]][1,0]

0.3517726550574086

In [46]:
X = np.random.rand(8,5)
X

array([[0.83713819, 0.50558805, 0.07709625, 0.28634448, 0.42165903],
       [0.24706172, 0.51436643, 0.64343314, 0.49987903, 0.24537608],
       [0.66996411, 0.13410019, 0.61956363, 0.13487905, 0.85767141],
       [0.53157419, 0.58703108, 0.27457374, 0.50105728, 0.13608429],
       [0.23561524, 0.52905431, 0.98974206, 0.53509453, 0.35908168],
       [0.93369707, 0.61307965, 0.09278851, 0.20250831, 0.50863883],
       [0.37066688, 0.72353315, 0.20997633, 0.58065429, 0.79179648],
       [0.46408827, 0.87612265, 0.23403422, 0.09149897, 0.57578855]])

In [48]:
X.transpose()


array([[0.83713819, 0.24706172, 0.66996411, 0.53157419, 0.23561524,
        0.93369707, 0.37066688, 0.46408827],
       [0.50558805, 0.51436643, 0.13410019, 0.58703108, 0.52905431,
        0.61307965, 0.72353315, 0.87612265],
       [0.07709625, 0.64343314, 0.61956363, 0.27457374, 0.98974206,
        0.09278851, 0.20997633, 0.23403422],
       [0.28634448, 0.49987903, 0.13487905, 0.50105728, 0.53509453,
        0.20250831, 0.58065429, 0.09149897],
       [0.42165903, 0.24537608, 0.85767141, 0.13608429, 0.35908168,
        0.50863883, 0.79179648, 0.57578855]])

In [49]:
X.T

array([[0.83713819, 0.24706172, 0.66996411, 0.53157419, 0.23561524,
        0.93369707, 0.37066688, 0.46408827],
       [0.50558805, 0.51436643, 0.13410019, 0.58703108, 0.52905431,
        0.61307965, 0.72353315, 0.87612265],
       [0.07709625, 0.64343314, 0.61956363, 0.27457374, 0.98974206,
        0.09278851, 0.20997633, 0.23403422],
       [0.28634448, 0.49987903, 0.13487905, 0.50105728, 0.53509453,
        0.20250831, 0.58065429, 0.09149897],
       [0.42165903, 0.24537608, 0.85767141, 0.13608429, 0.35908168,
        0.50863883, 0.79179648, 0.57578855]])

In [50]:
X = np.random.rand(2,8,5)
X

array([[[0.29635631, 0.03426078, 0.35641005, 0.64173672, 0.82434158],
        [0.44035378, 0.49402145, 0.95748016, 0.38624321, 0.53885176],
        [0.02058278, 0.1836885 , 0.49340767, 0.68182127, 0.78311759],
        [0.13035186, 0.35150039, 0.88045643, 0.6118491 , 0.74932204],
        [0.05936735, 0.77568901, 0.99195668, 0.76560234, 0.01150683],
        [0.47440298, 0.70084293, 0.78461687, 0.63438858, 0.55647243],
        [0.80013322, 0.30911528, 0.82109944, 0.37351317, 0.14454189],
        [0.52046321, 0.62844441, 0.51706355, 0.46004225, 0.04710793]],

       [[0.71187951, 0.84443438, 0.21872359, 0.82401892, 0.55015733],
        [0.66133003, 0.23000628, 0.5300154 , 0.5737578 , 0.57277642],
        [0.32041708, 0.37864965, 0.32836635, 0.1486115 , 0.96018037],
        [0.62956056, 0.17577157, 0.8531888 , 0.22285799, 0.38261814],
        [0.79461565, 0.05605104, 0.78055607, 0.02279529, 0.11713092],
        [0.10444048, 0.80637923, 0.76359072, 0.87675392, 0.19146894],
        [0.2313462

In [51]:
X.T

array([[[0.29635631, 0.71187951],
        [0.44035378, 0.66133003],
        [0.02058278, 0.32041708],
        [0.13035186, 0.62956056],
        [0.05936735, 0.79461565],
        [0.47440298, 0.10444048],
        [0.80013322, 0.23134626],
        [0.52046321, 0.94647932]],

       [[0.03426078, 0.84443438],
        [0.49402145, 0.23000628],
        [0.1836885 , 0.37864965],
        [0.35150039, 0.17577157],
        [0.77568901, 0.05605104],
        [0.70084293, 0.80637923],
        [0.30911528, 0.77625475],
        [0.62844441, 0.08629913]],

       [[0.35641005, 0.21872359],
        [0.95748016, 0.5300154 ],
        [0.49340767, 0.32836635],
        [0.88045643, 0.8531888 ],
        [0.99195668, 0.78055607],
        [0.78461687, 0.76359072],
        [0.82109944, 0.36407645],
        [0.51706355, 0.3489706 ]],

       [[0.64173672, 0.82401892],
        [0.38624321, 0.5737578 ],
        [0.68182127, 0.1486115 ],
        [0.6118491 , 0.22285799],
        [0.76560234, 0.02279529],
        