In [2]:
import numpy as np

In [9]:
X = np.array([10,20,30])
print(X, type(X), sep="\n")
print(X.ndim, X.shape, X.size, X.itemsize, X.nbytes, X.dtype, sep=",")

[10 20 30]
<class 'numpy.ndarray'>
1,(3,),3,4,12,int32


In [11]:
X = np.zeros(10)
print(X, type(X), sep="\n")
print(X.ndim, X.shape, X.size, X.itemsize, X.nbytes, X.dtype, sep=",")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
1,(10,),10,8,80,float64


In [12]:
X = np.ones(10)
print(X, type(X), sep="\n")
print(X.ndim, X.shape, X.size, X.itemsize, X.nbytes, X.dtype, sep=",")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
1,(10,),10,8,80,float64


In [13]:
X = np.empty(4)
print(X, type(X), sep="\n")
print(X.ndim, X.shape, X.size, X.itemsize, X.nbytes, X.dtype, sep=",")

[2.12199579e-314 8.44554325e-312 6.06712613e-321 8.44554325e-312]
<class 'numpy.ndarray'>
1,(4,),4,8,32,float64


In [14]:
X = np.ones((5,3))
print(X, type(X), sep="\n")
print(X.ndim, X.shape, X.size, X.itemsize, X.nbytes, X.dtype, sep=",")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
2,(5, 3),15,8,120,float64


In [15]:
X = np.ones((2,5,3))
print(X, type(X), sep="\n")
print(X.ndim, X.shape, X.size, X.itemsize, X.nbytes, X.dtype, sep=",")

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
3,(2, 5, 3),30,8,240,float64


In [16]:
X = np.ones((2,2,5,3))
print(X, type(X), sep="\n")
print(X.ndim, X.shape, X.size, X.itemsize, X.nbytes, X.dtype, sep=",")

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
<class 'numpy.ndarray'>
4,(2, 2, 5, 3),60,8,480,float64


In [17]:
X = np.ones((5,3), dtype = np.int32)
print(X, type(X), sep="\n")
print(X.ndim, X.shape, X.size, X.itemsize, X.nbytes, X.dtype, sep=",")

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
2,(5, 3),15,4,60,int32


In [18]:
X = X.astype(np.float64)
print(X, type(X), sep="\n")
print(X.ndim, X.shape, X.size, X.itemsize, X.nbytes, X.dtype, sep=",")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
2,(5, 3),15,8,120,float64


In [19]:
X = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
Y = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(X+Y, X-Y, X*Y, X/Y, sep="\n\n")

[[11 22 33 44]
 [55 66 77 88]]

[[ 9 18 27 36]
 [45 54 63 72]]

[[ 10  40  90 160]
 [250 360 490 640]]

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [20]:
X = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
Y = 20
print(X+Y, X-Y, X*Y, X/Y, sep="\n\n")

[[ 30  40  50  60]
 [ 70  80  90 100]]

[[-10   0  10  20]
 [ 30  40  50  60]]

[[ 200  400  600  800]
 [1000 1200 1400 1600]]

[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]]


In [22]:
X = np.ones((2,5,3))
Y = np.zeros((2,5,3))
print(X+Y, X-Y, X*Y, sep="\n\n")

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
