In [1]:
X = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
Y = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(X+Y, X-Y, X*Y, X/Y, sep="\n\n")

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
X = np.array([10, 20,30,40,50])
X

array([10, 20, 30, 40, 50])

In [5]:
print(np.sqrt(X), np.square(X), sep ="\n\n")

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

[ 100  400  900 1600 2500]


In [6]:
X = np.arange(1,11).reshape(5,2)
Y = np.arange(11,21).reshape(5,2)
print(X, Y, sep ="\n\n")

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [7]:
print(np.add(X, Y), np.subtract(X, Y), sep = "\n\n")

[[12 14]
 [16 18]
 [20 22]
 [24 26]
 [28 30]]

[[-10 -10]
 [-10 -10]
 [-10 -10]
 [-10 -10]
 [-10 -10]]


In [8]:
X = np.array([10,20,30,40,50,np.nan])
X

array([10., 20., 30., 40., 50., nan])

In [9]:
np.isnan(X)

array([False, False, False, False, False,  True])

In [10]:
np.isnan(X).any()

True

In [11]:
X = np.arange(1,11)
Y = np.arange(11,21)
x1,y1 = np.meshgrid(X,Y)
print(X, Y, x1, y1, sep = "\n\n")

[ 1  2  3  4  5  6  7  8  9 10]

[11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]

[[11 11 11 11 11 11 11 11 11 11]
 [12 12 12 12 12 12 12 12 12 12]
 [13 13 13 13 13 13 13 13 13 13]
 [14 14 14 14 14 14 14 14 14 14]
 [15 15 15 15 15 15 15 15 15 15]
 [16 16 16 16 16 16 16 16 16 16]
 [17 17 17 17 17 17 17 17 17 17]
 [18 18 18 18 18 18 18 18 18 18]
 [19 19 19 19 19 19 19 19 19 19]
 [20 20 20 20 20 20 20 20 20 20]]


In [16]:
Z = np.add(x1, y1)
print(Z, np.subtract(y1, x1), sep ="\n\n")

[[12 13 14 15 16 17 18 19 20 21]
 [13 14 15 16 17 18 19 20 21 22]
 [14 15 16 17 18 19 20 21 22 23]
 [15 16 17 18 19 20 21 22 23 24]
 [16 17 18 19 20 21 22 23 24 25]
 [17 18 19 20 21 22 23 24 25 26]
 [18 19 20 21 22 23 24 25 26 27]
 [19 20 21 22 23 24 25 26 27 28]
 [20 21 22 23 24 25 26 27 28 29]
 [21 22 23 24 25 26 27 28 29 30]]

[[10  9  8  7  6  5  4  3  2  1]
 [11 10  9  8  7  6  5  4  3  2]
 [12 11 10  9  8  7  6  5  4  3]
 [13 12 11 10  9  8  7  6  5  4]
 [14 13 12 11 10  9  8  7  6  5]
 [15 14 13 12 11 10  9  8  7  6]
 [16 15 14 13 12 11 10  9  8  7]
 [17 16 15 14 13 12 11 10  9  8]
 [18 17 16 15 14 13 12 11 10  9]
 [19 18 17 16 15 14 13 12 11 10]]


In [17]:
X = np.arange(1,5)
Y = np.arange(11,15)
Z = np.array([True, False, True, False])
print(X, Y, Z, np.where(Z, X, Y), sep="\n\n")

[1 2 3 4]

[11 12 13 14]

[ True False  True False]

[ 1 12  3 14]


In [18]:
X = np.arange(15).reshape((5,3))
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
print(np.mean(X), np.median(X), np.std(X), sep="\n")


7.0
7.0
4.320493798938574


In [20]:
print(np.mean(X, axis = 0), np.mean(X, axis = 1) , sep="\n")

[6. 7. 8.]
[ 1.  4.  7. 10. 13.]


#    Boolean Array

In [24]:
X = np.array([True, False, True, False])
X
print(X, X.dtype, sep="\n")

[ True False  True False]
bool


In [26]:
print(X.any(), X.all(), X.sum(), sep=",")

True,False,2


In [28]:
X = np.random.rand(10,9)
X

array([[0.8992038 , 0.5483911 , 0.32056156, 0.85136647, 0.7830558 ,
        0.61353339, 0.47099068, 0.47534735, 0.44447269],
       [0.20468713, 0.50176842, 0.94418037, 0.29270472, 0.75069615,
        0.84165649, 0.6435008 , 0.43226641, 0.66823757],
       [0.65853808, 0.79856219, 0.74938213, 0.15968063, 0.07408753,
        0.74586397, 0.52490209, 0.34750757, 0.17796032],
       [0.08093344, 0.52283138, 0.79774892, 0.60602448, 0.96391288,
        0.26225192, 0.97319109, 0.90778656, 0.81941181],
       [0.97320574, 0.19679409, 0.06855651, 0.85876456, 0.94348198,
        0.96521809, 0.63594053, 0.39630129, 0.53973765],
       [0.6277403 , 0.58466657, 0.68265562, 0.20156365, 0.91905914,
        0.55567827, 0.46220042, 0.22031403, 0.51554502],
       [0.11586124, 0.73444892, 0.48824602, 0.19497417, 0.89492074,
        0.30030768, 0.07230218, 0.25981037, 0.26609342],
       [0.21019173, 0.35411911, 0.32206449, 0.40495945, 0.96965799,
        0.43733337, 0.38231986, 0.41023446, 0.79405253],


In [30]:
print(X>0.5, (X>0.5).sum(), (X>0.5).all(), (X>0.5).any(), sep="\n")

[[ True  True False  True  True  True False False False]
 [False  True  True False  True  True  True False  True]
 [ True  True  True False False  True  True False False]
 [False  True  True  True  True False  True  True  True]
 [ True False False  True  True  True  True False  True]
 [ True  True  True False  True  True False False  True]
 [False  True False False  True False False False False]
 [False False False False  True False False False  True]
 [ True False  True  True False  True  True  True  True]
 [False  True  True  True  True  True  True False  True]]
53
False
True


#       Sorting

In [31]:
X = np.random.rand(5,4)
X

array([[0.22197201, 0.64541505, 0.78054969, 0.85865797],
       [0.3614991 , 0.72422486, 0.73073002, 0.72021073],
       [0.03513733, 0.64562347, 0.69386773, 0.15970393],
       [0.3638032 , 0.67315108, 0.42751865, 0.41435245],
       [0.3913692 , 0.26472751, 0.81105594, 0.32824882]])

In [32]:
print(np.sort(X, axis=0), np.sort(X, axis=1), np.sort(X, axis=None), sep="\n\n")

[[0.03513733 0.26472751 0.42751865 0.15970393]
 [0.22197201 0.64541505 0.69386773 0.32824882]
 [0.3614991  0.64562347 0.73073002 0.41435245]
 [0.3638032  0.67315108 0.78054969 0.72021073]
 [0.3913692  0.72422486 0.81105594 0.85865797]]

[[0.22197201 0.64541505 0.78054969 0.85865797]
 [0.3614991  0.72021073 0.72422486 0.73073002]
 [0.03513733 0.15970393 0.64562347 0.69386773]
 [0.3638032  0.41435245 0.42751865 0.67315108]
 [0.26472751 0.32824882 0.3913692  0.81105594]]

[0.03513733 0.15970393 0.22197201 0.26472751 0.32824882 0.3614991
 0.3638032  0.3913692  0.41435245 0.42751865 0.64541505 0.64562347
 0.67315108 0.69386773 0.72021073 0.72422486 0.73073002 0.78054969
 0.81105594 0.85865797]


#    Other Functions

In [35]:
X = np.array([10, 20, 30, 40, 50, 10, 20, 40, 100, 150, 30])
X

array([ 10,  20,  30,  40,  50,  10,  20,  40, 100, 150,  30])

In [34]:
np.unique(X)

array([ 10,  20,  30,  40,  50, 100, 150])

In [40]:
X = np.array([10, 20, 30, 40, 50, 10, 20, 40, 100, 150, 30])
Y = np.array([10, 20, 30, 40, 45, 56, 34])
print(np.in1d(X,Y), np.union1d(X,Y), np.setdiff1d(X,Y), sep="\n\n")

[ True  True  True  True False  True  True  True False False  True]

[ 10  20  30  34  40  45  50  56 100 150]

[ 50 100 150]


In [41]:
print(np.in1d(Y,X), np.union1d(Y,X), np.setdiff1d(Y,X), sep="\n\n")

[ True  True  True  True False False False]

[ 10  20  30  34  40  45  50  56 100 150]

[34 45 56]


#   File Save

In [42]:
X = np.random.rand(5,3)
X

array([[0.37957943, 0.06918734, 0.05379798],
       [0.40971114, 0.06739359, 0.91155539],
       [0.54504287, 0.20272847, 0.59236232],
       [0.61375856, 0.37114977, 0.76725207],
       [0.56493311, 0.00495258, 0.62653309]])

In [43]:
np.save("FileSave1.npy", X)

In [45]:
Y = np.load("FileSave1.npy")
Y

array([[0.37957943, 0.06918734, 0.05379798],
       [0.40971114, 0.06739359, 0.91155539],
       [0.54504287, 0.20272847, 0.59236232],
       [0.61375856, 0.37114977, 0.76725207],
       [0.56493311, 0.00495258, 0.62653309]])

In [49]:
X = np.random.rand(5,3)
Y = np.random.rand(5,3)
print(X, Y, sep="\n\n")

[[0.89249262 0.21723383 0.51858284]
 [0.11470331 0.33597517 0.7632861 ]
 [0.49487289 0.90090238 0.39350134]
 [0.79965634 0.10060833 0.43554404]
 [0.43687655 0.14019129 0.87851396]]

[[0.78180167 0.03572461 0.71332974]
 [0.75578209 0.73997916 0.01790989]
 [0.5654964  0.85980999 0.14009536]
 [0.62024286 0.18015847 0.0762287 ]
 [0.30721308 0.1720459  0.65814939]]


In [50]:
np.savez("FileSave2.npz", Xfile = X, Yfile = Y)

In [51]:
Z= np.load("FileSave2.npz")
print(Z['Xfile'], Z['Yfile'], sep="\n\n")

[[0.89249262 0.21723383 0.51858284]
 [0.11470331 0.33597517 0.7632861 ]
 [0.49487289 0.90090238 0.39350134]
 [0.79965634 0.10060833 0.43554404]
 [0.43687655 0.14019129 0.87851396]]

[[0.78180167 0.03572461 0.71332974]
 [0.75578209 0.73997916 0.01790989]
 [0.5654964  0.85980999 0.14009536]
 [0.62024286 0.18015847 0.0762287 ]
 [0.30721308 0.1720459  0.65814939]]
